### ISSUE TITLE
Keybinding conflicts occurred

### ISSUE THREAD

**Issue by mniewrzal** [pdt-eg/Core-Plugin#145] opened 2016-06-23 11:56 UTC
PHP Development Tools (PDT) 4.1.0.201606161653
PDT Extensions 0.22.2.201606170654

A conflict occurred for CTRL+SHIFT+N:
Binding(CTRL+SHIFT+N,
    ParameterizedCommand(Command(org.eclipse.php.debug.ui.commands.InspectDelegate,Inspect,
        Inspect result of evaluating selected text,
        Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3ae81b53,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.php.ui.phpEditorScope,,,system)
Binding(CTRL+SHIFT+N,
    ParameterizedCommand(Command(org.pdtextensions.core.ui.command.phpcsfixer,Run PHP-CS-Fixer,
        Run PHP-CS-Fixer on files and folders,
        Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7a7d25ca,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.php.core.phpsource,,,system)

**Comment by zulus** [comment] 2016-06-24 09:08
any proposition for alternative key binding?

**Comment by mniewrzal** [comment] 2016-06-24 09:42
Maybe something like Shift+Alt+X F. Its quite complicated but I don't know how often its used.

For example Run CLI Application has Shift+Alt+X H, Run PHP Web Application Shift+Alt+X W.

**Comment by zulus** [comment] 2018-03-26 15:01
Duplicate of #127

**Closed by zulus** 2018-03-26 15:01 UTC
