### ISSUE TITLE
String index out of range: 1

### ISSUE THREAD

**Issue by youjumpiwatch** [pdt-eg/Core-Plugin#47] opened 2013-04-15 06:45 UTC
Note:
I'm using the *OLD* stable version from [p2.dubture.com](http://p2.dubture.com/)

When I tried to generate setters & getters, it reported two same errors: "string index out of range:1"

Here's the minimal source code file that can reproduce these errors:

    <?php
    class MyClass {
	private $_client = null;
    }

Here's eclipse error log:

    
    !ENTRY org.eclipse.ui 4 4 2013-04-15 14:40:45.771
    !MESSAGE Conflicting handlers for org.eclipse.wst.sse.ui.toggle.comment: {org.eclipse.php.internal.ui.actions.PHPToggleLineCommentHandler@6c592ddc} vs {org.eclipse.wst.sse.ui.internal.handlers.ToggleLineCommentHandler@52d1fe16}
    
    !ENTRY org.eclipse.jface 4 2 2013-04-15 14:40:47.203
    !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
    !STACK 0
    java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    	at java.lang.String.substring(String.java:1907)
    	at com.dubture.pdt.core.util.Inflector.camelCase(Inflector.java:145)
    	at com.dubture.pdt.ui.util.GetterSetterUtil.prepareField(GetterSetterUtil.java:138)
    	at com.dubture.pdt.ui.util.GetterSetterUtil.getGetterName(GetterSetterUtil.java:124)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterEntry.getIdentifier(GenerateGettersHandler.java:510)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterEntry.getName(GenerateGettersHandler.java:530)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterLabelProvider.getText(GenerateGettersHandler.java:173)
    	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.getText(WrappedViewerLabelProvider.java:108)
    	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.update(WrappedViewerLabelProvider.java:164)
    	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:152)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:953)
    	at org.eclipse.jface.viewers.CheckboxTreeViewer.doUpdateItem(CheckboxTreeViewer.java:120)
    	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:113)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1033)
    	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:485)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2167)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:848)
    	at org.eclipse.jface.viewers.AbstractTreeViewer$1.run(AbstractTreeViewer.java:823)
    	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:797)
    	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:644)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1770)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1780)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1075)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1056)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandAll(AbstractTreeViewer.java:1045)
    	at com.dubture.pdt.ui.dialog.GetterSetterDialog.createTreeViewer(GetterSetterDialog.java:236)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.createDialogArea(CheckedTreeSelectionDialog.java:290)
    	at com.dubture.pdt.ui.dialog.GetterSetterDialog.createDialogArea(GetterSetterDialog.java:102)
    	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:760)
    	at org.eclipse.jface.window.Window.create(Window.java:431)
    	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1089)
    	at org.eclipse.ui.dialogs.SelectionStatusDialog.create(SelectionStatusDialog.java:153)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.access$superCreate(CheckedTreeSelectionDialog.java:247)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.access$0(CheckedTreeSelectionDialog.java:246)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog$1.run(CheckedTreeSelectionDialog.java:272)
    	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.create(CheckedTreeSelectionDialog.java:270)
    	at org.eclipse.jface.window.Window.open(Window.java:790)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.open(CheckedTreeSelectionDialog.java:242)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler.execute(GenerateGettersHandler.java:236)
    	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:601)
    	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:231)
    	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:212)
    	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:131)
    	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:171)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:831)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:724)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:708)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:647)
    	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:601)
    	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    
    !ENTRY org.eclipse.jface 4 2 2013-04-15 14:40:47.238
    !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
    !STACK 0
    java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    	at java.lang.String.substring(String.java:1907)
    	at com.dubture.pdt.core.util.Inflector.camelCase(Inflector.java:145)
    	at com.dubture.pdt.ui.util.GetterSetterUtil.prepareField(GetterSetterUtil.java:138)
    	at com.dubture.pdt.ui.util.GetterSetterUtil.getSetterName(GetterSetterUtil.java:116)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterEntry.getIdentifier(GenerateGettersHandler.java:511)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterEntry.getName(GenerateGettersHandler.java:539)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler$GetterSetterLabelProvider.getText(GenerateGettersHandler.java:173)
    	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.getText(WrappedViewerLabelProvider.java:108)
    	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.update(WrappedViewerLabelProvider.java:164)
    	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:152)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:953)
    	at org.eclipse.jface.viewers.CheckboxTreeViewer.doUpdateItem(CheckboxTreeViewer.java:120)
    	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:113)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1033)
    	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:485)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2167)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:848)
    	at org.eclipse.jface.viewers.AbstractTreeViewer$1.run(AbstractTreeViewer.java:823)
    	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:797)
    	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:644)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1770)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1780)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1075)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1056)
    	at org.eclipse.jface.viewers.AbstractTreeViewer.expandAll(AbstractTreeViewer.java:1045)
    	at com.dubture.pdt.ui.dialog.GetterSetterDialog.createTreeViewer(GetterSetterDialog.java:236)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.createDialogArea(CheckedTreeSelectionDialog.java:290)
    	at com.dubture.pdt.ui.dialog.GetterSetterDialog.createDialogArea(GetterSetterDialog.java:102)
    	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:760)
    	at org.eclipse.jface.window.Window.create(Window.java:431)
    	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1089)
    	at org.eclipse.ui.dialogs.SelectionStatusDialog.create(SelectionStatusDialog.java:153)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.access$superCreate(CheckedTreeSelectionDialog.java:247)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.access$0(CheckedTreeSelectionDialog.java:246)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog$1.run(CheckedTreeSelectionDialog.java:272)
    	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.create(CheckedTreeSelectionDialog.java:270)
    	at org.eclipse.jface.window.Window.open(Window.java:790)
    	at org.eclipse.ui.dialogs.CheckedTreeSelectionDialog.open(CheckedTreeSelectionDialog.java:242)
    	at com.dubture.pdt.ui.actions.GenerateGettersHandler.execute(GenerateGettersHandler.java:236)
    	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:601)
    	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:231)
    	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:212)
    	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:131)
    	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:171)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:831)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:724)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:708)
    	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:647)
    	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:601)
    	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    
    !ENTRY org.eclipse.ui 4 4 2013-04-15 14:40:47.266
    !MESSAGE Conflicting handlers for org.eclipse.wst.sse.ui.toggle.comment: {org.eclipse.php.internal.ui.actions.PHPToggleLineCommentHandler@6c592ddc} vs {org.eclipse.wst.sse.ui.internal.handlers.ToggleLineCommentHandler@52d1fe16}
    
    !ENTRY org.eclipse.ui 4 4 2013-04-15 14:40:48.643
    !MESSAGE Conflicting handlers for org.eclipse.wst.sse.ui.toggle.comment: {org.eclipse.php.internal.ui.actions.PHPToggleLineCommentHandler@6c592ddc} vs {org.eclipse.wst.sse.ui.internal.handlers.ToggleLineCommentHandler@52d1fe16}
    
    !ENTRY org.eclipse.ui 4 4 2013-04-15 14:40:50.462
    !MESSAGE Conflicting handlers for org.eclipse.wst.sse.ui.toggle.comment: {org.eclipse.php.internal.ui.actions.PHPToggleLineCommentHandler@6c592ddc} vs {org.eclipse.wst.sse.ui.internal.handlers.ToggleLineCommentHandler@52d1fe16}

**Comment by zulus** [comment] 2015-02-14 13:57
I'm not able to reproduce in current version. Closing.

**Closed by zulus** 2015-02-14 13:57 UTC
